export const POLICY_TYPES = [
  { id: "LIFE_TERM", label: "Term Life Insurance", group: "LIFE" },
  { id: "LIFE_ULIP", label: "ULIP (Unit Linked Insurance)", group: "INVESTMENT" },
  { id: "PENSION_NPS", label: "NPS / Pension Scheme", group: "INVESTMENT" },
  { id: "LIFE_ENDOWMENT", label: "Traditional / Endowment Life", group: "INVESTMENT" },
  { id: "HEALTH_FLOATER", label: "Health Floater (Family)", group: "HEALTH" },
  { id: "HEALTH_INDIVIDUAL", label: "Health Individual", group: "HEALTH" },
  { id: "HEALTH_SUPER_TOPUP", label: "Super Top-up Health", group: "HEALTH" },
  { id: "HEALTH_CRITICAL_ILLNESS", label: "Critical Illness Rider / Plan", group: "HEALTH" },
  { id: "MOTOR_FOUR_WHEELER", label: "Motor (4-Wheeler)", group: "MOTOR" },
  { id: "MOTOR_TWO_WHEELER", label: "Motor (2-Wheeler)", group: "MOTOR" },
  { id: "COMMERCIAL_VEHICLE", label: "Commercial Vehicle", group: "MOTOR" },
  { id: "HOME_PROPERTY", label: "Home & Property", group: "GENERAL" },
  { id: "CYBER_LIABILITY", label: "Cyber / Liability Insurance", group: "GENERAL" },
  { id: "GENERAL_OTHER", label: "Other General Insurance", group: "GENERAL" },
];

export const INITIAL_FORM = {
  policyNumber: "",
  providerName: "",
  policyType: "HEALTH_FLOATER",
  planName: "",
  policyHolder: "",
  sumAssured: "",
  premiumAmount: "",
  premiumFrequency: "YEARLY",
  policyTermYears: "1",
  premiumPayingTermYears: "1",
  startDate: new Date().toISOString().slice(0, 10),
  nextDueDate: new Date().toISOString().slice(0, 10),
  maturityDate: "",
  status: "ACTIVE",
  paymentMode: "NET_BANKING",
  taxBenefitSection: "80D",
  notes: "",
  nominee: { name: "", relation: "", sharePercentage: 100 },
  insuredPersons: [{ name: "", relation: "Self" }],
  investmentDetails: {
    pranOrFolio: "",
    fundManager: "",
    fundOption: "",
    unitsHeld: "",
    latestNav: "",
    currentValuation: "",
    totalInvestedTillDate: "",
    equityAllocationPct: 0,
    debtAllocationPct: 0,
    lockInUntil: "",
  },
  healthDetails: {
    tpaName: "",
    deductibleAmount: "",
    cumulativeBonusNCB: "",
    roomRentLimit: "Single Private Room / No Capping",
    copayPercentage: 0,
    cashlessCardNumber: "",
  },
  motorDetails: {
    vehicleNumber: "",
    makeModel: "",
    idv: "",
    engineNumber: "",
    chassisNumber: "",
    hasZeroDepreciation: false,
    hasEngineProtector: false,
    ncbPercentage: 0,
  },
  servicingAgent: {
    name: "",
    phone: "",
    portalUrl: "",
  },
};